### ISSUE TITLE
Bricked?

### ISSUE THREAD

**Issue by prashantkamdar** [pewpew-game/pewpew-m4-v8#4]
I was experimenting with the pewpew4 using makecode.
I loaded a different game from the makecode forums, entered the pewpew4 in usb mode using https://github.com/pewpew-game/pewpew-m4-v8/issues/2#issuecomment-758154267 and copied the file on the new usb disk.

It ran well and after a while, I shutdown the console.
When I started it back up, (without shorting the pins) it again started in the usb mode and I shut it down.

Now, whenever I start the console, it stays blank and shows a white screen.
Even after connecting to usb after shorting the R and - pins, nothing happens.

Is it bricked? Can I recover?

**Comment by niutech** [comment]
Have you tried shorting the **R** and **-** pins **twice in a row** to get to the bootloader mode? If nothing happens, you can still recover the bootloader using SWD and J-Link, see the [guide](https://pewpew.readthedocs.io/en/latest/pewpew-m4/assembly.html#bootloader).

**Comment by prashantkamdar** [comment]
Yes, I tried the shorting of the pins.
That is how I was able to get few other games running from makecode.

I guess I need to reflash the bootloader.
Will this programmer work? https://robu.in/product/st-link-v2-programmer-for-stm8-and-stm32/?gclid=EAIaIQobChMI3bye7aqM7wIVxiMrCh3kIg0QEAQYASABEgIL4PD_BwE

**Comment by niutech** [comment]
I don't know, but see answers to [this question](https://electronics.stackexchange.com/questions/250664/can-i-use-st-link-programmer-for-non-st-chips/386726).

**Comment by prashantkamdar** [comment]
Could you link me to a known flasher which you may be aware of / use?
I will find the compatible one basis that.

**Comment by niutech** [comment]
You can use Segger J-Link EDU Mini.

**Comment by prashantkamdar** [comment]
thanks, I was successfully able to re-program it
however, with after uploading new game, the buttons don't work
also, whenever connected to usb on pc, it always runs in bootloader mode 


![90](https://user-images.githubusercontent.com/2802365/110233578-d010c700-7f4a-11eb-9e15-5e7fb48cdb37.jpg)
![70](https://user-images.githubusercontent.com/2802365/110233585-d606a800-7f4a-11eb-8d75-bf8c6a4b05e5.jpg)

**Comment by prashantkamdar** [comment]
proof videos here of the problem described above:
https://imgur.com/a/vLbLi1p

**Comment by prashantkamdar** [comment]
@deshipu 
I had bought this on tindie in June of 2020. (order #197268)
As I've described above, I had put a makecode game and it ran for some time.
But after a few power cycles, the console seemed bricked.

I was able to successfully recover it with @niutech 's suggestions, but now facing new problems.

- The buttons don't work on any game
- Whenever connected to USB on PC, it always runs in bootloader mode
- proof videos of the problem described above: https://imgur.com/a/vLbLi1p

I messaged makerfabs on tindie (since they're the seller) describing the same problem requesting for a replacement, but haven't heard yet.

Can you help me debug/correct this issue (if it is possible?).
Alternatively, can you help me get a replacement, please?

**Comment by niutech** [comment]
IMO you should complain to Makerfabs, maybe your device is faulty? Meanwhile, have you tried flashing [CircuitPython](https://circuitpython.org/board/pewpew_m4/)? Does it work?

**Comment by prashantkamdar** [comment]
Yes, @niutech I agree with you - Makerfabs should try and resolve this and I already messaged them but haven't heard back.
Hence, was hoping for the original creator's intervention.

To your question - yes, I had already tried out circuitpython and tried a few simple examples.
Unfortunately, the buttons in the circuitpython examples also don't work.

If it's not a hardware problem, my guess is that that erasing and then re-uploading the bootloader has corrupted something on the system.

**Comment by prashantkamdar** [comment]
OK, I have a quick update.
After re-flashing a couple of times the different circuitypython uf2 versions from the official circuitypython download section, it seems that there is life back again.
I tried out some of the methods defined [here](https://pewpew.readthedocs.io/en/latest/pew.html), it seems that the buttons are indeed working!
However, uploading to makecode uf2 games, none of the buttons get recognised.

My hunch is, that the bootloader is different when it ships versus the one given in this repo.
@niutech, @deshipu is this hunch worth looking into or is it some other problem? Can you guys give me a working bootloader.bin file from your working console? (see if it is working with makecode games, too)

**Comment by deshipu** [comment]
Can you try downloading the uf2 bootloader update from https://circuitpython.org/board/pewpew_m4/ and flashing it in bootloader mode?

**Comment by prashantkamdar** [comment]
Oh wow!
That did the trick.
I flashed the above mentioned v.3.13 bootloader and then again loaded the makecode arcade games; the button mappings now work in the games!

Does it mean that the bootloader mentioned in this repo ([.bin file](https://github.com/pewpew-game/pewpew-m4-v8/blob/master/pewpew-m4-v8-bootloader.bin)) is an older version?

**Comment by deshipu** [comment]
I think so, I will remove it. Sorry for the confusion.

**Comment by prashantkamdar** [comment]
No problem.
Thanks a lot @deshipu and @niutech !
